[settings]
bloatie     = true

#+-------------+
#| TOP LEFT    |
#+-------------+

[[widgets]]
type            = "Meter"
title           = "HD1"
theme           = 0

reading         = true
meter           = true

max_command     = ["bash", "/home/gorg/bin/sh/bloaty/disk_size", "/"] 
value_command   = ["bash",  "/home/gorg/bin/sh/bloaty/disk_free", "/"] 
frequency       = 60
right           = false
bottom          = false
unit            = "mb"

[[widgets]]
type            = "Meter"
title           = "HD2"
theme           = 0

reading         = true
meter           = true

max_command     = ["bash", "/home/gorg/bin/sh/bloaty/disk_size", "/mnt/dump/"]
value_command   = ["bash", "/home/gorg/bin/sh/bloaty/disk_free", "/mnt/dump/"] 
frequency       = 60
right           = false
bottom          = false
unit            = "mb"

[[widgets]]
type            = "Seperator"
title           = "Service Status:"

right           = false
bottom          = false

[[widgets]]
type            = "Indicator"
title           = " Server is running "

command         = ["bash", "/home/gorg/bin/sh/bloaty/indicatortest"]
frequency       = 1

right           = false
bottom          = false

#+-------------+
#| BOTTOM LEFT |
#+-------------+

[[widgets]]
type            = "Meter"
theme           = 1

reading         = false
meter           = true

prefix          = "Year "
max_command     = ["echo", "52"]
value_command   = ["bash", "/home/gorg/bin/sh/bloaty/weeknr"] 
frequency       = 60
right           = false
bottom          = true
unit            = ""

[[widgets]]
type            = "Meter"
theme           = 1

reading         = false
meter           = true

prefix          = "Week "
max_command     = ["echo", "7"]
value_command   = ["bash", "/home/gorg/bin/sh/bloaty/weekday_nr"] 
frequency       = 60
right           = false
bottom          = true
unit            = ""

[[widgets]]
type            = "Meter"
theme           = 1

reading         = false
meter           = true

prefix          = "Day  "
max_command     = ["echo", "24"]
value_command   = ["bash", "/home/gorg/bin/sh/bloaty/hourinday"] 
frequency       = 60
right           = false
bottom          = true
unit            = ""

[[widgets]]
type            = "Seperator"
title           = "Date and stuff:"
right           = false
bottom          = true

#+--------------+
#| BOTTOM RIGHT |
#+--------------+
[[widgets]]
type            = "Meter"
theme           = 1

reading         = false
meter           = true

prefix          = "RAM       "
max_command     = ["bash", "/home/gorg/bin/maxmem"] 
value_command   = ["memcheck"] 
frequency       = 60
right           = true
bottom          = true
unit            = "mb"

[[widgets]]
type            = "Meter"
theme           = 1

reading         = false
meter           = true

prefix          = "CPU-temp  "
max_command     = ["echo", "85000"]
value_command   = ["bash", "/home/gorg/bin/sh/bloaty/cputemp"] 
frequency       = 60
right           = true
bottom          = true
unit            = ""

[[widgets]]
type            = "Meter"
theme           = 1

reading         = false
meter           = true

prefix          = "CPU-avg   "
max_command     = ["echo", "155000"]
value_command   = ["bash", "/home/gorg/bin/sh/bloaty/cputemp" ]
frequency       = 60
right           = true
bottom          = true
unit            = ""

[[widgets]]
type            = "Seperator"
title           = "Sysinfo:"
right           = true
bottom          = true

